// Cleanup
GET https://neve-demo-import.test/index.php?rest_route=/ti-sites-lib/v1/cleanup
Cookie: wp-settings-time-1=1620896779; wordpress_test_cookie=WP%20Cookie%20check; wordpress_logged_in_8f6101c9c3d6e485a425e92a554f537c=admin%7C1621069302%7CLNmScQodLMysBWMEwyHckNXjjOucGokVGl7kiCyPoQF%7C66ded12223a5cc048c352abb6b469c459998ad11b26d4c1f85b42e2a0a5d7cdd
X-WP-Nonce: 729fd85bf1
###