name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen # 18.x
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn run build
          composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_THEMEISLE_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_THEMEISLE_USERNAME }}
